### ISSUE TITLE
TLC5922 adaptation ?

### ISSUE THREAD

**Issue by schmurtzm** [2splat/arduino-TLC5926#2]
Hi,

I try to hack an old device which contain an TLC5922 ([datasheet](https://www.ti.com/lit/ds/symlink/tlc5922.pdf)) led driver driven by SPI.

On this device there is 5 RGB lights, each light is composed in reality of 3 leds : R,G,B and each of this colored led is controlled by an output of the TLC5922.

On this device, the TLC5922 is connected like this :
![image](https://user-images.githubusercontent.com/7110113/145498504-df311306-48c6-453b-b59c-bb39f6106af6.png)

[My arduino's forum post about this subject.](https://forum.arduino.cc/t/looking-for-library-to-control-tlc5922/934165)

If you have any advice... 😉 

Thank you.

**Comment by awgrover** [comment]
This library could serve as a model for a tlc5922 library. I don't know how different the tlc5922 is, and I don't have the time to work on it (sorry!). There are some libraries written by others that you might prefer. I specifically layered this one for raw (less memory) versus "optimized" (less communication) updates.

You would have to look at the datasheet and compare this library's functions. It seems likely that you could do one function at a time. Start with an empty class and add methods.

Adafruit has some libraries that you should consider building upon: 
[https://www.arduino.cc/reference/en/libraries/adafruit-busio/](https://www.arduino.cc/reference/en/libraries/adafruit-busio/)
[https://github.com/adafruit/Adafruit_BusIO](https://github.com/adafruit/Adafruit_BusIO)

Most important advice:

* Don't use delay(). Use the non-blocking pattern (e.g. [https://www.arduino.cc/en/Tutorial/BuiltInExamples/BlinkWithoutDelay](https://www.arduino.cc/en/Tutorial/BuiltInExamples/BlinkWithoutDelay) )
* delayMicroseconds() is ok for small amounts

If you have specific questions, I can make some time to answer you. However, I haven't been monitoring my messages here (I'll look at a better notification), so I might be slow to answer. (I should notice notifications quicker now, we'll see)

**Comment by schmurtzm** [comment]
Hi, thank you for your nice answer ! I finally found [a code](https://github.com/sebastienhouzet/nabaztag-source-code/blob/master/hardware/Outils/SolutionD%C3%A9mo/Projet-IAR/led.c#L30) which has helped me to control the TLC5922. Not as handy to use as a library but enough for what I want to do. May be I will try to adapt it in a library later...
I keep your advice about non-blocking pattern, thank you!
